"""Initial migration with OAuth support

Revision ID: 2c623ae27cdb
Revises: 
Create Date: 2025-05-13 22:07:40.936096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c623ae27cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(length=500), nullable=False),
    sa.Column('back', sa.String(length=500), nullable=False),
    sa.Column('option_1', sa.String(length=200), nullable=False),
    sa.Column('option_2', sa.String(length=200), nullable=False),
    sa.Column('option_3', sa.String(length=200), nullable=False),
    sa.Column('option_4', sa.String(length=200), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('front_language', sa.String(length=2), nullable=True),
    sa.Column('back_language', sa.String(length=2), nullable=True),
    sa.Column('audio_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('language_preference', sa.String(length=20), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_practice_date', sa.DateTime(), nullable=True),
    sa.Column('total_practices', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('incorrect_answers', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('preferred_practice_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_plan', sa.String(length=20), nullable=True),
    sa.Column('payment_history', sa.JSON(), nullable=True),
    sa.Column('learning_direction', sa.String(length=10), nullable=True),
    sa.Column('subscription_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('oauth_google', sa.String(length=100), nullable=True),
    sa.Column('oauth_google_email', sa.String(length=120), nullable=True),
    sa.Column('oauth_google_name', sa.String(length=120), nullable=True),
    sa.Column('oauth_google_picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_google'),
    sa.UniqueConstraint('oauth_google_email')
    )
    op.create_table('o_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('answer_given', sa.String(length=200), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exercise')
    op.drop_table('o_auth')
    op.drop_table('user')
    op.drop_table('card')
    # ### end Alembic commands ###
